name: My First Pipeline

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2 - Show files
      - name: Show Files
        run: ls

      # Step 3 - Create a file
      - name: Create File
        run: echo "Hello from Pipeline!" > output.txt

      # Step 4 - Read the file
      - name: Read File
        run: cat output.txt

      # Step 5 - Show system info
      - name: System Info
        run: |
          echo "OS Info:"
          uname -a
          echo "Disk Space:"
          df -h
          echo "Memory:"
          free -h

      # Step 6 - Show date
      - name: Show Date
        run: date
