name: My First Pipeline

on:
  push:
    branches: [main]   

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Files
        run: ls

      - name: Say Hello
        run: echo "Pipeline Working!"

      - name: Show Date
        run: date
